version: 2

sphinx:
  configuration: docs/conf.py
  # fail_on_warning might generate hard to fix error, in this case it can be
  # disabled but this also means those errors will fail silently, choose wisely.
  fail_on_warning: true

conda:
  environment: environment-rtd.yml
