# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py
  # fail_on_warning might generate hard to fix error, in this case it can be
  # disabled but this also means those errors will fail silently, choose wisely.
  fail_on_warning: true

build:
  os: ubuntu-22.04
  tools:
    python: "mambaforge-22.9"
  jobs:
    pre_build:
      - env SPHINX_APIDOC_OPTIONS="members,undoc-members,show-inheritance,noindex" sphinx-apidoc -o docs/apidoc --private --module-first src/ravenpy
      - sphinx-build -M gettext docs docs/_build
      - sphinx-build -b linkcheck docs/ _build/linkcheck || true

formats:
  - pdf

conda:
  environment: environment-docs.yml

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - dev
        - docs
