name: ravenpy-docs
channels:
- conda-forge
- defaults
dependencies:
  - python >=3.12,<3.13
  - raven-hydro >=0.3.1,<1.0
#  - autodoc-pydantic  # disabled
  - birdy
  - cairosvg >=2.6.0
  - cartopy >=0.23.0
  - click >=8.0.0
  - clisops >=0.13.0
  - gcsfs
  - gdal >=3.1
# Needed for notebooks/HydroShare_integration.ipynb
# See: https://github.com/CSHS-CWRA/RavenPy/pull/326
#  - "hsclient",
  - intake <2.0.0
  - intake-esm >=2023.07.07
  - intake-xarray
  - ipykernel
  - ipyleaflet
  - ipython >=8.5.0
  - jupyter-cache
  - jupyter_client
  - jupytext
  - matplotlib-base >=3.6.0
  - myst-nb
  - nbsphinx
  - netCDF4 <=1.6.5
  - numpy >=1.23.0,<2.0.0
  - notebook
  - pandoc
  - pydantic >=2.0
  - pymetalink >=6.5.2
  - s3fs
  - salib
  - seaborn
  - sphinx >=7.1.0
  - sphinx-autoapi
  - sphinx-click
  - sphinx-codeautolink >=0.16.2
  - sphinx-copybutton
  - sphinx-rtd-theme >=1.0
  - sphinxcontrib-svg2pdfconverter >=1.2.3
  - typing_extensions
  - xarray >=2023.11.0
#  - xesmf  # mocked
