envlist = [
  "lint",
  {product = [{prefix = "py3.", start = 10, stop = 14}]},
  "docs"
]
skip_missing_interpreters = true

[env.docs]
description = "Build the documentation with makefile under {basepython}"
labels = ["docs"]
dependency_groups = ["docs"]
extras = []
commands = [
  ["make", "build-docs"]
]
commands_post = []
allowlist_externals = ["make"]

[env.gis]
description = "Run tests with extras under {basepython}"
deps = ["numpy >= 1.25.0", "gdal == {env:GDAL_VERSION}.*", "setuptools >= 71.0"]
extras = ["gis", "raven-hydro"]
commands = [
  ["python", "-m", "pip", "install", "--no-user", "--upgrade", "--force-reinstall", "--no-deps", "--no-binary", "gdal", "gdal[numpy]=={env:GDAL_VERSION}.*"],
  ["python", "-c", "import ravenpy.testing.utils as rtu; rtu.populate_testing_data(branch=\"{env:RAVEN_TESTDATA_BRANCH}\")"],
  ["pytest", "{posargs}"]
]

[env.lint]
description = "Run code quality compliance tests under {basepython}"
labels = ["lint"]
skip_install = true
dependency_groups = ["lint"]
extras = []
commands = [
  ["make", "lint"]
]
commands_post = []
allowlist_externals = ["make"]

[env_run_base]
description = "Run tests with pytest under {basepython}"
setenv = {PYTEST_ADDOPTS = "--color=yes --numprocesses=logical --durations=10 --cov=ravenpy --cov-report=lcov", PYTHONPATH = "{toxinidir}", TOX = "{envname}"}
passenv = ["CI", "COVERALLS_*", "GDAL_VERSION", "GITHUB_*", "LD_LIBRARY_PATH", "RAVEN_*"]
download = true
install_command = ["python", "-m", "pip", "install", "--no-user", "{opts}", "{packages}"]
dependency_groups = ["test"]
extras = ["raven-hydro"]
deps = [
  {replace = "if", condition = "env.RAVEN_HYDRO_UPSTREAM_BRANCH", then = ["git+https://github.com/Ouranosinc/raven-hydro.git@{env:RAVEN_HYDRO_UPSTREAM_BRANCH}"], extend = true}
]
commands_pre = [
  ["python", "-m", "pip", "list"],
  ["python", "-m", "pip", "check"]
]
commands = [
  ["python", "-c", "import ravenpy.testing.utils as rtu; rtu.populate_testing_data(branch=\"{env:RAVEN_TESTDATA_BRANCH}\")"],
  ["pytest", "{posargs}"]
]
commands_post = [
  ["coverage", "report"]
]

[gh.python]
"3.10" = ["py3.10"]
"3.11" = ["py3.11"]
"3.12" = ["py3.12"]
"3.13" = ["py3.13"]
"3.14" = ["py3.14"]
