name: Question/Support
description: Ask for help from the developers
labels: [ "support" ]

body:
  - type: textarea
    id: setup-information
    attributes:
      label: Setup Information
      description: |
        What software versions are you running? Example:
        - ravenpy version: 0.55.0-gamma
        - Python version: 4.2
        - Operating System: Nutmeg Linux 12.34 | macOS 11.0 "Redmond"
      value: |
        - ravenpy version:
        - Python version:
        - Operating System:
  - type: textarea
    id: description
    attributes:
      label: Context
      description: Describe what you were trying to get done. Tell us what happened, what went wrong, and what you expected to happen.
