name: Verify Testing Data

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    paths:
      - .github/workflows/main.yml

permissions:
  contents: read

jobs:
  use-latest-tag:
    name: Check Latest raven-testdata Tag
    runs-on: ubuntu-latest
    if: |
     (github.event.pull_request.head.repo.full_name == github.event.pull_request.base.repo.full_name)
    permissions:
      pull-requests: write
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443
            github.com:443
      - name: Checkout Repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false
      - name: Find raven-testdata Tag and CI Testing Branch
        run: |
          RAVEN_TESTDATA_TAG="$( \
          git -c 'versionsort.suffix=-' \
          ls-remote --exit-code --refs --sort='version:refname' --tags https://github.com/Ouranosinc/raven-testdata '*.*.*' \
          | tail --lines=1 \
          | cut --delimiter='/' --fields=3)"
          echo "RAVEN_TESTDATA_TAG=${RAVEN_TESTDATA_TAG}" >> $GITHUB_ENV
          RAVEN_TESTDATA_BRANCH="$(grep -E "RAVEN_TESTDATA_BRANCH" .github/workflows/main.yml | cut -d ' ' -f4)"
          echo "RAVEN_TESTDATA_BRANCH=${RAVEN_TESTDATA_BRANCH}" >> $GITHUB_ENV
      - name: Report Versions Found
        run: |
          echo "Latest raven-testdata tag: ${RAVEN_TESTDATA_TAG}"
          echo "Tag for raven-testdata in CI: ${RAVEN_TESTDATA_BRANCH}"
        env:
          RAVEN_TESTDATA_TAG: ${{ env.RAVEN_TESTDATA_TAG }}
          RAVEN_TESTDATA_BRANCH: ${{ env.RAVEN_TESTDATA_BRANCH }}
      - name: Find Comment
        uses: peter-evans/find-comment@b30e6a3c0ed37e7c023ccd3f1db5c6c0b0c23aad # v4.0.0
        id: fc
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: It appears that this Pull Request modifies the `main.yml` workflow.
      - name: Compare Versions
        if: ${{( env.RAVEN_TESTDATA_TAG != env.RAVEN_TESTDATA_BRANCH )}}
        uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
        with:
          script: |
            core.setFailed('Configured `raven-testdata` tag is not `latest`.')
      - name: Update Failure Comment
        if: ${{ failure() }}
        uses: peter-evans/create-or-update-comment@e8674b075228eee787fea43ef493e45ece1004c9 # v5.0.0
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            > [!WARNING]
            > It appears that this Pull Request modifies the `main.yml` workflow.

            On inspection, it seems that the `RAVEN_TESTDATA_BRANCH` environment variable is set to a tag that is not the latest in the `Ouranosinc/raven-testdata` repository.

            This value must match the most recent tag (`${{ env.RAVEN_TESTDATA_TAG }}`) in order to merge this Pull Request.

            If this PR depends on changes in a new testing dataset branch, be sure to tag a new version of `Ouranosinc/raven-testdata` once your changes have been merged to its `main` branch.
          edit-mode: replace
      - name: Update Success Comment
        if: ${{ success() }}
        uses: peter-evans/create-or-update-comment@e8674b075228eee787fea43ef493e45ece1004c9 # v5.0.0
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            > [!NOTE]
            > It appears that this Pull Request modifies the `main.yml` workflow.

            On inspection, the `RAVEN_TESTDATA_BRANCH` environment variable is set to the most recent tag (`${{ env.RAVEN_TESTDATA_TAG }}`).

            No further action is required.
          edit-mode: replace
